spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/test
    username: postgres
    password: 12345
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

server:
  port: 9090
